### ISSUE TITLE
ERROR: No matching distribution found for dutycalls-sdk==0.1.2

### ISSUE THREAD

**Issue by robbm1** [transceptor-technology/python-dutycalls-sdk#1]
I get this error when installing the library:

```
Collecting dutycalls-sdk==0.1.2
  Using cached dutycalls_sdk-0.1.2.tar.gz (4.1 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/rob/miniconda3/envs/gcs-backup-check/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-22vf_n50/dutycalls-sdk_22f083a68ae14b949c7db855da6ef9df/setup.py'"'"'; __file__='"'"'/tmp/pip-install-22vf_n50/dutycalls-sdk_22f083a68ae14b949c7db855da6ef9df/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-903z5ljf
         cwd: /tmp/pip-install-22vf_n50/dutycalls-sdk_22f083a68ae14b949c7db855da6ef9df/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-22vf_n50/dutycalls-sdk_22f083a68ae14b949c7db855da6ef9df/setup.py", line 8, in <module>
        from dutycalls import __version__
      File "/tmp/pip-install-22vf_n50/dutycalls-sdk_22f083a68ae14b949c7db855da6ef9df/dutycalls/__init__.py", line 4, in <module>
        from .client import Client
      File "/tmp/pip-install-22vf_n50/dutycalls-sdk_22f083a68ae14b949c7db855da6ef9df/dutycalls/client.py", line 14, in <module>
        from aiohttp import ClientSession, ClientResponse, BasicAuth
    ModuleNotFoundError: No module named 'aiohttp'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6a/91/ceccd329002db219859f85975c6fb5628a33ce9637eddd2a10bfcdaa643a/dutycalls_sdk-0.1.2.tar.gz#sha256=66d4d9b5457487f97c36e0aa73578f940688f07a345f86caba7dae5b18c9fb42 (from https://pypi.org/simple/dutycalls-sdk/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement dutycalls-sdk==0.1.2 (from versions: 0.1.0, 0.1.1, 0.1.2)
ERROR: No matching distribution found for dutycalls-sdk==0.1.2
```

**Comment by joente** [comment]
It is not possible to read the `__version__` from the dutycalls library ***and*** importing the Client in the `__init__.py` since other dependencies are not installed at this time. 

Since we don't want to break the module, use a try..except around the Client import to solve the issue
